services:
  - type: web
    name: song-scribe-api-flow
    env: python
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    healthCheckInitialDelaySeconds: 5
    healthCheckIntervalSeconds: 10
    autoSuspend: false
