services:
  - type: web
    name: song-scribe-api-flow
    env: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python direct_migrations.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    healthCheckInitialDelaySeconds: 30
    healthCheckIntervalSeconds: 15
    autoSuspend: false
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
