services:
  - type: web
    name: song-scribe-api-flow
    env: python
    buildCommand: pip install -r requirements.txt && python run_migrations.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    healthCheckInitialDelaySeconds: 10
    healthCheckIntervalSeconds: 15
    autoSuspend: false
