"""add_typeorder_and_persoonlijk_verhaal_to_orders

Revision ID: ac5c3189725c
Revises: b89338895eb8
Create Date: 2025-06-25 10:32:54.990493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5c3189725c'
down_revision = 'b89338895eb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('typeOrder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'typeOrder')
    # ### end Alembic commands ###
